name: CI

on:
  push:
    paths-ignore:
      - "docs/**"
      - "data/**"
      - ".md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "data/**"
      - "*.md"
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: ESLint
        run: pnpm lint

      - name: Test types
        run: pnpm test:types

      - name: Build
        run: pnpm build

      - name: CLI
        run: pnpm production-calendar
